### ISSUE TITLE
Cannot migrate away from Serial using IDENTITY columns

### ISSUE THREAD

**Issue by patrickklaeren** [discord-csharp/MODiX#679]
With the upgrade to 3.0, the Postgres driver for EF introduced IDENTITY columns. This leads to the following error when trying to add/run migrations.
```
Failed executing DbCommand (15ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE "Tags" ALTER COLUMN "Id" TYPE bigint;
ALTER TABLE "Tags" ALTER COLUMN "Id" SET NOT NULL;
ALTER SEQUENCE "Tags_Id_seq" RENAME TO "Tags_Id_old_seq";
ALTER TABLE "Tags" ALTER COLUMN "Id" DROP DEFAULT;
ALTER TABLE "Tags" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY;
PERFORM setval('"Tags_Id_seq"', nextval('"Tags_Id_old_seq"'), false);
DROP SEQUENCE "Tags_Id_old_seq";
Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "PERFORM"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 973
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 416
   at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 298
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1178
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 977
   at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 959
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
  Exception data:
    Severity: ERROR
    SqlState: 42601
    MessageText: syntax error at or near "PERFORM"
    Position: 1
    File: scan.l
    Line: 1134
    Routine: scanner_yyerror
42601: syntax error at or near "PERFORM"
```

Relevant: http://www.npgsql.org/efcore/release-notes/3.0.html

See npgsql/efcore.pg#1157

**Comment by Inzanit** [comment]
Blocked until the fix in the pgsql driver has been fixed.

**Comment by Sutarodo** [comment]
This is the issue we're waiting on:
https://github.com/npgsql/efcore.pg/issues/1157

**Comment by patrickklaeren** [comment]
Looks like this is sorted now and resolved as per the closed issue in the EF Core repo.
