### ISSUE TITLE
MessageLogBehavior throws if the message is not cached

### ISSUE THREAD

**Issue by Jay-Madden** [discord-csharp/MODiX#735]
`A MessageUpdated handler has thrown an unhandled exception.:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Modix.Services.Core.MessageLogBehavior.FormatMessage(String input) in /Users/JayMadden/modix_base/modix/Modix.Services/Core/MessageLogBehavior.cs:line 52
   at Modix.Services.Core.MessageLogBehavior.HandleMessageEdit(Cacheable2 cachedOriginal, IMessage updated, ISocketMessageChannel channel) in /Users/JayMadden/modix_base/modix/Modix.Services/Core/MessageLogBehavior.cs:line 115
   at Discord.EventExtensions.InvokeAsync[T1,T2,T3](AsyncEvent1 eventHandler, T1 arg1, T2 arg2, T3 arg3)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func1 action)`

.GetOrDownloadAsync() needs to be called on the message object

**Comment by patrickklaeren** [comment]
As part of a new effort to refocus on priorities, I will close this. If you feel this is imperative to the bot, a new issue can be opened to supersede this.
